name: Pull Request to main
run-name: Pull Request to main

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: write

jobs:
  release:
    env:
      INCREMENT_VERSION: ""
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable conditionally
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" == "develop" ]; then
            echo "INCREMENT_VERSION=minor" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.head.ref }}" == "bugfixes" ]; then
            echo "INCREMENT_VERSION=patch" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: chill-viking/npm-ci@latest

      - name: Config Git
        uses: fregante/setup-git-user@v2

      - name: Switch to main branch
        run: |
          git fetch origin
          git switch main

      - name: Version bump
        if: ${{ env.INCREMENT_VERSION != '' }}
        run: npm run release:$INCREMENT_VERSION

  build:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get short commit SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        id: repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and tag API image
        run: docker build -t ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}/api:${{ steps.short-sha.outputs.sha }} ./api

      - name: Build and tag Sender image
        run: docker build -t ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}/sender:${{ steps.short-sha.outputs.sha }} ./sender

      - name: Build and tag Thread image
        run: docker build -t ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}/thread:${{ steps.short-sha.outputs.sha }} ./thread

      - name: Push API image
        run: docker push ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}/api:${{ steps.short-sha.outputs.sha }}

      - name: Push Sender image
        run: docker push ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}/sender:${{ steps.short-sha.outputs.sha }}

      - name: Push Thread image
        run: docker push ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}/thread:${{ steps.short-sha.outputs.sha }}
